---
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-service"
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.general.ports.containerPort }}
    targetPort: {{ .Values.general.ports.containerPort }}
  type: NodePort