{{- $root := . -}}
{{- range $name, $config := .Values.deployables }}
{{- if eq $config.controller "cronjob" }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  schedule: {{ $config.schedule | quote }}
  concurrencyPolicy: {{ $config.concurrencyPolicy | default "Forbid" }}
  startingDeadlineSeconds: {{ $config.startingDeadlineSeconds | default "600" }}
  successfulJobsHistoryLimit: 1
  {{- if or $config.suspend $.Values.global.suspendCrons }}
  suspend: true
  {{- else }}
  suspend: false
  {{- end }}
  jobTemplate:
    spec:
      {{- if $config.backoffLimit }}
      backoffLimit: {{ $config.backoffLimit }}
      {{- end }}
      template:
        metadata:
          annotations:
            ad.datadoghq.com/tags: '[{"source":"{{ $.Values.global.source }}","service":"{{ $name }}"}]'
            cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
            linkerd.io/inject: 'disabled'
            {{- range $key, $value := $config.annotations }}
            {{ $key }}: {{ quote $value }}
            {{- end }}
        spec:
          containers:
          - name: {{ $name }}
            {{- if $config.image }}
            image: "{{ $config.image.repository }}:{{ $config.image.tag | default "latest" }}"
            {{- else }}
            image: "{{ $.Values.global.image.repository }}:{{ $.Values.global.image.tag | default "latest" }}"
            {{- end }}
            imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
            env:
              - name: CRONJOB
                value: "true"
              - name: ENVCONSUL_ONCE
                value: "true"
              {{- $envVars := mergeOverwrite (dict) ($.Values.global.envVars | default dict) ($config.envVars | default dict)}}
              {{- range $key, $value := $envVars}}
              - name: {{ $key }}
                value: {{ $value | quote }}
              {{- end }}
              {{- include "k8s.variables" . | nindent 14 }}
              - name: PROJECT
                value: {{ $.Chart.Name }}
            resources:
              {{- $config.resources | toYaml | nindent 14 }}
            {{ if $config.command -}}
            command:
              {{- range $config.command }}
              - {{ . }}
              {{- end }}
            {{- end }}
            {{ if $config.args -}}
            args:
              {{- range $config.args }}
              - {{ . }}
              {{- end }}
            {{- end }}
          restartPolicy: {{ $config.restartPolicy | default "OnFailure" }}
          serviceAccountName: {{ $.Chart.Name }}
          {{- if $config.affinity}}
          affinity:
            {{ $config.affinity | toYaml | nindent 12 | trim }}
          {{- else if $.Values.global.affinity }}
          affinity:
            {{ $.Values.global.affinity | toYaml | nindent 12 | trim }}
          {{- end }}
{{- end }}
{{- end }}
