{{- range $key,$value := .Values.global.secret.secrets }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $.Release.Name }}-{{ $key }}
spec:
  itemPath: "vaults/{{$.Values.global.secret.vaultid}}/items/{{ $value }}"
{{- end }}